### ISSUE TITLE
Question. Does this plugin work w/ `expo-updates`?

### ISSUE THREAD

**Issue by o-alexandrov** [Malaa-tech/expo-custom-assets#1]
Hello, thank you for the plugin.
Have you checked whether this plugin works with [expo-updates](https://docs.expo.dev/versions/latest/sdk/updates)?

**Comment by mzaien** [comment]
hello @o-alexandrov , I did not get what exactly do you mean but if you meant that the new assets are pushed with `expo-update` I would guess it does not because as far as my Knowledge expo-updates/codepush just push Javascript code not other assets or native o

**Comment by o-alexandrov** [comment]
I also think it doesn’t, because assets are added individually by modifying the native files:
https://github.com/Malaa-tech/expo-custom-assets/blob/5bd5f1d8aba6303551eeb2ec8bbd22102e9c5f5e/src/index.ts#L132

https://github.com/Malaa-tech/expo-custom-assets/blob/5bd5f1d8aba6303551eeb2ec8bbd22102e9c5f5e/src/index.ts#L64

---

I think for this plugin to work with `expo-updates`, this plugin needs to `require()` individual files and somehow make `metro` to bundle it (for example by modifying `assetExts`):
- described in [this article](https://docs.expo.dev/guides/assets)

---

If you ignore support for expo-updates, I think you should add a directory as a group, not individual files
- described in [this article](https://yelotofu.com/react-native-load-local-static-site-inside-webview-2b93eb1c4225)
