### ISSUE TITLE
[Feature Request] Support for `ignoredPattern`

### ISSUE THREAD

**Issue by VidocqH** [Malaa-tech/expo-custom-assets#11]
Description:
Currently, the plugin copies all files from the specified asset directories. However, there's no way to exclude certain files that we don't want in the final bundle (like .DS_Store files on macOS).

Feature Request:
Add a new configuration option `ignoredPattern` that accepts a regex pattern string to exclude matching files during the asset copying process.

Example:
```json
{
  "plugins": [
    [
      "expo-custom-assets",
      {
        "assetsPaths": ["./path-to-your-asset-folder"],
        "assetsDirName": "Assets",
        "ignoredPattern": "\\.DS_Store$"  // Ignore .DS_Store
      }
    ]
  ]
}

**Comment by mzaien** [comment]
Hello @VidocqH  great idea ! 
can you try it with version 1.4.0?
