### ISSUE TITLE
expo-custom-assets does not support Expo SDK 50 and 51

### ISSUE THREAD

**Issue by antoniogoulao** [Malaa-tech/expo-custom-assets#4]
expo-custom-assets does not support Expo SDK 50 and 51.

With release of Expo 51, soon Expo 49 will stop being supported.

Going through the docs, [Expo 50](https://expo.dev/changelog/2024/01-18-sdk-50) and [Expo 51](https://expo.dev/changelog/2024/05-07-sdk-51) do not introduce breaking changes impacting the usage of this config-plugin.

**Comment by mzaien** [comment]
@antoniogoulao Thank you for the help I approved and merged your pr, I'll be releasing it today
