### ISSUE TITLE
Support web assets for .riv

### ISSUE THREAD

**Issue by t1gu1** [Malaa-tech/expo-custom-assets#7]
Works great on mobile for IOS/Android!

I made things works on web devellopement, but I see that the assets `.riv` aren't  present in the `web` final static build.

Just write that command `expo export -p web` and go check the `.build` folder.

In my `app.config` i have
```
{
...
web: {
      bundler: "metro",
      output: "static",
      favicon: "./assets/images/favicon.png",
    },
...
}
```
Maybe it is juste something I have to do on my side.
I'll give info if I found something.

**Comment by mzaien** [comment]
Hello @t1gu1 thanks for the report , just want to ask did you make a prebuild before exporting the web version

TBH I haven’t check the web support but will give it a try after your answer

**Comment by t1gu1** [comment]
Oh I just found why it's not present in web.
We have to add a `require("@/assets/rive/bonsoir.riv");` somewhere in the code to include file in the bundle, even if it's not used.

**Comment by mzaien** [comment]
> Oh I just found why it's not present in web. We have to add a `require("@/assets/rive/bonsoir.riv");` somewhere in the code to include file in the bundle, even if it's not used.

is this an issue from expo? or there is it mentioned in their docs

**Comment by t1gu1** [comment]
It's more a "ME" problem from what a found..

I'll share my expérience here if others found it.
For the web, assets has to be `require()` somewhere in the code to be present in the `assets` final `build` folder.

So for the web, I did that so select the good ressource: (In my RiveAdapter.web.tsx)

```
const [assets] = useAssets([
    require("assets/rive/boussole3.riv"),
    require("assets/rive/mapcanada3.riv"),
  ]);

  const source = assets?.find((asset) =>
    asset.name.includes(resourceName)
  )?.uri;
```
